import Head from "next/head";

import Footer from "@components/Layout/Footer";
import {
  StyledContent,
  StyledLayout,
  StyledSpace,
} from "@components/StyledComponents";
// import { getImg } from "@utils/getImg";

import wallpaper from "../../../public/svg/wallpaper.svg";
import Header from "./Header";

interface LayoutProps {
  children: JSX.Element | JSX.Element[];
}

const Layout = ({ children }: LayoutProps): JSX.Element => {
  return (
    <>
      <Head>
        {/* //TODO: add translations for the meta tags! */}
        <title>Course Recommender System</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/img/favicon/favicon.ico" rel="icon" />
      </Head>
      <StyledLayout>
        <Header />
        <StyledContent
          style={{
            backgroundImage: `url(${wallpaper.src})`,
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            // minHeight: "100vh",
            // height: "100vh",
            // width: "100vw",
          }}
        >
          {/* <div
            style={{
              height: "100vh",
              position: "fixed",
              width: "100%",
              zIndex: -1,
            }}
          >
            <Image
              alt="wallpaper"
              draggable={false}
              src={getImg("wallpaper")}
              style={{ objectFit: "cover" }}
              fill
            />
          </div> */}
          <StyledSpace direction="vertical">{children}</StyledSpace>
        </StyledContent>
        <Footer />
      </StyledLayout>
    </>
  );
};

export default Layout;
