import Head from "next/head";

import Footer from "@components/Layout/Footer";
import {
  StyledContent,
  StyledLayout,
  StyledSpace,
} from "@components/StyledComponents";

import Header from "./Header";

interface LayoutProps {
  children: JSX.Element | JSX.Element[];
}

const Layout = ({ children }: LayoutProps): JSX.Element => {
  return (
    <>
      <Head>
        {/* //TODO: add translations for the meta tags! */}
        <title>Course Recommender System</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/img/favicon/favicon.ico" rel="icon" />
      </Head>
      <StyledLayout>
        <Header />
        <StyledContent>
          <StyledSpace direction="vertical">{children}</StyledSpace>
        </StyledContent>
        <Footer />
      </StyledLayout>
    </>
  );
};

export default Layout;
