import { Card, Col, Row } from "antd";
import { NextPage } from "next";
import Head from "next/head";

import Image from "@components/Image";
import Layout from "@components/Layout";

import iProtect from "../../public/img/iprotect-mobile.png";

const { Meta } = Card;

const CardComponent = (
  <Card cover={<Image alt="iProtect" src={iProtect} />} hoverable>
    <Meta description="Made using Next.js" title="iProtect website" />
  </Card>
);

const HomePage: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="Generated by create next app" name="description" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon.ico" rel="icon" />
    </Head>
    <Layout>
      <Row gutter={[16, 16]}>
        {new Array(5).fill(CardComponent).map((item) => (
          <Col md={12} sm={24} xl={6}>
            {item}
          </Col>
        ))}
      </Row>
    </Layout>
  </>
);

export default HomePage;
