import { ReactNode } from "react";

import { InstagramOutlined, FacebookOutlined } from "@ant-design/icons";
import { Col, Row, Space, Typography } from "antd";
import useTranslation from "next-translate/useTranslation";
import Head from "next/head";
import { useRouter } from "next/router";

import {
  StyledContent,
  StyledFooter,
  StyledHeader,
  StyledLayout,
  StyledLink,
} from "@components/StyledComponents";

import LocaleSwitcher from "./LocaleSwitcher";

type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps): JSX.Element => {
  const { Text } = Typography;
  const { t, lang } = useTranslation("common");
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Course Recommender System</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <StyledLayout>
        <StyledHeader>
          <Row justify="space-between">
            <Col>
              <Space>
                <StyledLink href="/" primary>
                  Home
                </StyledLink>
                <StyledLink href="/courses" primary>
                  Courses
                </StyledLink>
              </Space>
            </Col>
            <Col>
              <Space>
                <LocaleSwitcher />
                <StyledLink href="/login" primary>
                  Login
                </StyledLink>
                <StyledLink href="/register" primary>
                  Register
                </StyledLink>
              </Space>
            </Col>
          </Row>
        </StyledHeader>
        <StyledContent>
          <Space direction="vertical">{children}</Space>
        </StyledContent>
        <StyledFooter>
          <Row justify="space-between">
            <Col>
              <Text>
                Made by nbean452 on{" "}
                <StyledLink href="https://github.com/nbean452">
                  Github
                </StyledLink>
              </Text>
            </Col>
            <Col>
              <Space direction="horizontal">
                <StyledLink href="https://www.instagram.com">
                  <InstagramOutlined />
                </StyledLink>
                <StyledLink href="https://www.facebook.com">
                  <FacebookOutlined />
                </StyledLink>
              </Space>
            </Col>
          </Row>
        </StyledFooter>
      </StyledLayout>
    </>
  );
};

export default Layout;
